# Generated by Django 5.2.10 on 2026-01-28 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Endereço/Local')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU')),
                ('ean', models.CharField(blank=True, max_length=13, null=True, verbose_name='Código de Barras (EAN)')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('KG', 'Quilo'), ('L', 'Litro'), ('CX', 'Caixa'), ('RL', 'Rolo'), ('PCT', 'Pacote')], default='UN', max_length=5)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('controla_lote', models.BooleanField(default=True, verbose_name='Controla Lote e Validade?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacao', verbose_name='Localização no Estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo (Unitário)')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantidade_inicial', models.IntegerField()),
                ('quantidade_atual', models.IntegerField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ESGOTADO', 'Esgotado'), ('VENCIDO', 'Vencido')], default='ATIVO', max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Nome do Solicitante')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('responsavel_saida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_realizados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_dono', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
