# Generated by Django 6.0.1 on 2026-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PECA', 'Peça de Reposição'), ('EQUIP', 'Equipamento'), ('FERRA', 'Ferramenta')], max_length=5)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
