# Generated by Django 6.0.1 on 2026-01-19 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_saida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
