# Generated by Django 5.2.10 on 2026-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_emprestimo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor de Venda (Unitário)'),
        ),
    ]
