# Generated by Django 5.2.10 on 2026-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_saidaestoque_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_saida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Saída'),
        ),
    ]
