# Generated by Django 6.0.1 on 2026-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_saidaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='locacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localização'),
        ),
    ]
