# Generated by Django 5.2.10 on 2026-02-26 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_emprestimo_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Saída'),
        ),
    ]
