# Generated by Django 6.0.1 on 2026-06-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_emprestimo_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.lote', verbose_name='Lote de Origem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('KG', 'Quilo'), ('L', 'Litro'), ('CX', 'Caixa'), ('RL', 'Rolo'), ('PCT', 'Pacote'), ('GL', 'Galão'), ('BG', 'Bag')], default='UN', max_length=5),
        ),
    ]
