# Generated by Django 6.0.1 on 2026-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_locacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='locacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização na Estante'),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
    ]
