# Generated by Django 6.0.1 on 2026-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_locacao_alter_saidaestoque_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5, verbose_name='Estoque Mínimo'),
        ),
    ]
