# Generated by Django 6.0.1 on 2026-07-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_saidaestoque_lote_alter_produto_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Imposto/Regime')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
            ],
        ),
    ]
