# Generated by Django 5.2.10 on 2026-07-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_aliquotaimposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade no Estoque')),
                ('preco_custo_futuro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo Futuro')),
                ('quantidade_futura', models.IntegerField(blank=True, null=True, verbose_name='Quantidade da Compra Futura')),
                ('frete_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frete')),
                ('tipo_frete', models.CharField(default='valor', max_length=15, verbose_name='Tipo de Frete')),
                ('outros_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Outros Custos')),
                ('tipo_outros', models.CharField(default='valor', max_length=15, verbose_name='Tipo de Outros Custos')),
                ('aliquota_nome', models.CharField(max_length=100, verbose_name='Nome do Imposto')),
                ('aliquota_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('margem_desejada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margem Desejada (%)')),
                ('metodo', models.CharField(default='inside', max_length=10, verbose_name='Método (Markup)')),
                ('preco_sugerido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Sugerido')),
                ('preco_praticado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Praticado')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro Líquido (R$)')),
                ('margem_realizada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margem Realizada (%)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Simulação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
