# Generated by Django 6.0.1 on 2026-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_simulacaopreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='codigo_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Código da Baixa Agrupada'),
        ),
    ]
