# Generated by Django 6.0.1 on 2026-09-21 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_saidaestoque_codigo_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CPF / CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Completo')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Limite de Crediário (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(default=1, verbose_name='Nº da Parcela')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela (R$)')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='estoque.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento', 'numero_parcela'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoCrediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Recebido (R$)')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('OUTRO', 'Outro')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='estoque.contareceber', verbose_name='Conta / Parcela')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_crediario', to='estoque.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Pagamento de Crediário',
                'verbose_name_plural': 'Pagamentos de Crediário',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venda', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Código da Venda')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('valor_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (R$)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('CREDIARIO', 'Crediário / A Prazo')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='CONCLUIDA', max_length=20, verbose_name='Status da Venda')),
                ('status_pagamento', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente (Em Aberto)'), ('PARCIAL', 'Parcialmente Pago'), ('CANCELADO', 'Cancelado')], default='PAGO', max_length=20, verbose_name='Status do Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='estoque.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='estoque.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor / Operador')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (R$)')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.lote', verbose_name='Lote de Origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto')),
                ('saida_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='estoque.saidaestoque')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.venda')),
            ],
        ),
        migrations.AddField(
            model_name='contareceber',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='estoque.venda', verbose_name='Venda de Origem'),
        ),
    ]
