# Generated by Django 5.2.16 on 2026-09-21 21:10

import django.db.models.deletion
from django.db import migrations, models


def popular_nome_produto(apps, schema_editor):
    ItemVenda = apps.get_model('estoque', 'ItemVenda')
    for item in ItemVenda.objects.select_related('produto').all():
        if item.produto and not item.nome_produto:
            item.nome_produto = item.produto.nome
            item.save(update_fields=['nome_produto'])


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_cliente_contareceber_pagamentocrediario_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.RunPython(popular_nome_produto, migrations.RunPython.noop),
    ]
