# Generated by Django 5.2.16 on 2026-09-21 21:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_itemvenda_nome_produto_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Vigência da Assinatura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status_assinatura',
            field=models.CharField(choices=[('TRIAL', 'Período de Testes (3 dias)'), ('ATIVA', 'Assinatura Ativa'), ('VENCIDA', 'Vencida / Expirada'), ('CANCELADA', 'Cancelada')], default='TRIAL', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trial_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Período de Testes'),
        ),
        migrations.CreateModel(
            name='PagamentoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Valor da Assinatura (R$)')),
                ('metodo', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago (Pix / Cartão)'), ('MANUAL_ADMIN', 'Ativação Manual / Cortesia')], default='MERCADO_PAGO', max_length=30, verbose_name='Método')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado / Falhou'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('mp_preference_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID da Preferência MP')),
                ('mp_payment_id', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='ID do Pagamento MP')),
                ('mp_init_point', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Checkout MP')),
                ('dias_concedidos', models.IntegerField(default=30, verbose_name='Dias Concedidos')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações / Detalhes')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_assinatura', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Pagamento de Assinatura',
                'verbose_name_plural': 'Pagamentos de Assinatura',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
