# Generated by Django 5.2.16 on 2026-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_produto_disponivel_venda_produto_preco_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacaopreco',
            name='aliquota_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Imposto'),
        ),
    ]
