# Generated by Django 5.2.16 on 2026-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_simulacaopreco_aliquota_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoassinatura',
            name='mp_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Order ID MP (ORDTST...)'),
        ),
    ]
