# Generated by Django 6.0.1 on 2026-09-25 21:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def populate_existing_loans(apps, schema_editor):
    Emprestimo = apps.get_model('estoque', 'Emprestimo')
    HistoricoEmprestimo = apps.get_model('estoque', 'HistoricoEmprestimo')
    for emp in Emprestimo.objects.all():
        if emp.devolvido:
            emp.quantidade_devolvida = emp.quantidade
            emp.save(update_fields=['quantidade_devolvida'])
        HistoricoEmprestimo.objects.create(
            emprestimo=emp,
            usuario=emp.responsavel_saida,
            tipo_acao='CRIACAO',
            quantidade=emp.quantidade,
            saldo_restante=Decimal('0.00') if emp.devolvido else emp.quantidade,
            observacao=f"Empréstimo inicial para {emp.solicitante}.",
            data_registro=emp.data_saida or django.utils.timezone.now()
        )
        if emp.devolvido:
            HistoricoEmprestimo.objects.create(
                emprestimo=emp,
                usuario=emp.responsavel_devolucao or emp.responsavel_saida,
                tipo_acao='DEVOLUCAO_TOTAL',
                quantidade=emp.quantidade,
                saldo_restante=Decimal('0.00'),
                observacao="Devolução total confirmada.",
                data_registro=emp.data_devolucao or emp.data_saida or django.utils.timezone.now()
            )


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_pagamentoassinatura_mp_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_saida'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='codigo_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Código da Baixa/Empréstimo Agrupado'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_devolvida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantidade Devolvida'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False, verbose_name='Totalmente Devolvido?'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='estoque.lote', verbose_name='Lote de Origem'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade Emprestada'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='responsavel_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Saída'),
        ),
        migrations.CreateModel(
            name='HistoricoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Empréstimo Criado / Saída'), ('DEVOLUCAO_PARCIAL', 'Devolução Parcial'), ('DEVOLUCAO_TOTAL', 'Devolução Total'), ('OBSERVACAO', 'Observação / Anotação'), ('CANCELAMENTO', 'Cancelamento')], default='CRIACAO', max_length=20, verbose_name='Tipo de Ação')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantidade Movimentada')),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo Pendente Após Ação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Detalhes / Observação')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='estoque.emprestimo', verbose_name='Empréstimo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Empréstimo',
                'verbose_name_plural': 'Históricos de Empréstimos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.RunPython(populate_existing_loans, migrations.RunPython.noop),
    ]
