# Generated by Django 6.0.1 on 2026-09-28 18:06

import django.db.models.deletion
from django.db import migrations, models


def criar_configuracao_para_empresas_existentes(apps, schema_editor):
    Empresa = apps.get_model('estoque', 'Empresa')
    ConfiguracaoEmpresa = apps.get_model('estoque', 'ConfiguracaoEmpresa')
    for emp in Empresa.objects.all():
        ConfiguracaoEmpresa.objects.get_or_create(empresa=emp)


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_alter_emprestimo_options_emprestimo_codigo_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_emprestimos', models.BooleanField(default=True, help_text='Controle de ferramentas, cautelas a colaboradores e histórico de devoluções.', verbose_name='Módulo de Empréstimos & Cautelas')),
                ('modulo_vendas_pdv', models.BooleanField(default=True, help_text='Frente de caixa rápido, registro de vendas no balcão e emissão de cupons.', verbose_name='Módulo de Vendas / PDV')),
                ('modulo_clientes_crediario', models.BooleanField(default=True, help_text='Cadastro de clientes, limites de crédito, parcelamento próprio e contas a receber.', verbose_name='Módulo de Clientes & Crediário')),
                ('modulo_simulador_precos', models.BooleanField(default=True, help_text='Tabela de preços de venda, simulador de formação de preços (markup/margem) e relatórios de precificação.', verbose_name='Preços & Simulações de Custo')),
                ('modulo_controle_lotes', models.BooleanField(default=True, help_text='Rastreamento por lote, data de fabricação, validade e alertas de vencimento.', verbose_name='Controle Avançado de Lotes & Validades')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_obj', to='estoque.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Módulos da Empresa',
                'verbose_name_plural': 'Configurações de Módulos das Empresas',
            },
        ),
        migrations.RunPython(criar_configuracao_para_empresas_existentes, migrations.RunPython.noop),
    ]
