# Generated by Django 6.0.1 on 2026-09-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_configuracaoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='descricao_adicional',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Descrição do Adicional (ex: Frete, Taxa de Entrega)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Acréscimo / Adicional (R$)'),
        ),
    ]
