# Generated by Django 6.0.1 on 2026-09-29 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_sanitizar_dados_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentocrediario',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('CREDIARIO', 'Crediário / A Prazo')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do Cheque')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco (Nome ou Código)')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta Corrente')),
                ('titular', models.CharField(max_length=150, verbose_name='Nome do Titular / Emitente')),
                ('cpf_cnpj_titular', models.CharField(blank=True, max_length=25, null=True, verbose_name='CPF/CNPJ do Titular')),
                ('telefone_titular', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone de Contato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Cheque (R$)')),
                ('tipo', models.CharField(choices=[('A_VISTA', 'À Vista'), ('PRE_DATADO', 'Pré-datado')], default='PRE_DATADO', max_length=20, verbose_name='Tipo de Cheque')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_compensacao', models.DateField(verbose_name='Bom para / Data de Compensação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Em Carteira (A Compensar)'), ('COMPENSADO', 'Compensado'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Cheque')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data da Baixa / Compensação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='estoque.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='estoque.empresa')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='estoque.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['data_compensacao', '-data_cadastro'],
            },
        ),
    ]
