# Generated by Django 6.0.1 on 2026-10-02 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_pagamentocrediario_forma_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('CREDIARIO', 'Crediário / A Prazo'), ('MULTIPLO', 'Múltiplo / Combinado')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Pagamento Imediato / Entrada'), ('ADIANTAMENTO', 'Adiantamento de Pagamento'), ('PARCELA', 'Baixa de Parcela')], default='ENTRADA', max_length=20, verbose_name='Tipo de Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('CREDIARIO', 'Crediário / A Prazo'), ('OUTRO', 'Outro')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_venda', to='estoque.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='estoque.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Venda',
                'ordering': ['data_pagamento', 'id'],
            },
        ),
    ]
